Repository BiteSpeed-Dev/chatwoot, pull requests merged in 2024-09, with the labels that each got.

#101 feat: conversation import optimization
  app/builders/conversation_import.rb
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/accounts/conversations_controller.rb
  app/finders/message_finder.rb
  app/javascript/dashboard/api/inbox/message.js
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/store/modules/conversations/actions.js
Labels: ready to merge

#104 fix: message fetching for external created at conflicts
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/mixins/conversations.js
Labels: ready to merge

#105 feat: improved wa report handling logic
  app/builders/messages/message_builder.rb
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  config/routes.rb
Labels: ready to merge, api-inbox

#107 feat: prevent duplicate messages
  app/builders/messages/message_builder.rb
Labels: ready to merge

#111 feat: moved destroy message api under accounts
  app/controllers/api/v1/accounts/conversations/messages_controller.rb
  app/controllers/api/v1/accounts_controller.rb
  app/policies/account_policy.rb
  config/routes.rb
Labels: ready to merge, api-inbox, delete messages

#112 feat: agent wise label and agent reports
  app/builders/v2/report_builder.rb
  app/controllers/devise_overrides/token_validations_controller.rb
  app/helpers/report_helper.rb
  app/jobs/agent_report_job.rb
  app/jobs/daily_conversation_report_job.rb
  app/jobs/daily_inbox_report_job.rb
  app/jobs/label_report_job.rb
  app/mailers/administrator_notifications/channel_notifications_mailer.rb
  app/views/mailers/administrator_notifications/channel_notifications_mailer/daily_agent_report.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/daily_label_report.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/monthly_agent_report.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/monthly_label_report.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/weekly_agent_report.liquid
  app/views/mailers/administrator_notifications/channel_notifications_mailer/weekly_label_report.liquid
  config/schedule.yml
Labels: ready to merge

#81 fixed for duplicate messages in chat
  app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
  app/javascript/dashboard/mixins/conversations.js
Labels: stale
